services:
  db_todo:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: db_todo

    ports:
      - "3306:3306"

    env_file:
      - ./.env

    volumes:
      - db_todo:/var/lib/mysql
      - ./db_script:/docker-entrypoint-initdb.d

volumes:
  db_todo: